###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    redis:
      image: redis:alpine
      container_name: example-api-redis

    mysql:
      image: mysql:5.7
      container_name: example-api-mysql
      working_dir: /var/www
      volumes:
        - .:/var/www
      environment:
        - MYSQL_ROOT_PASSWORD=app
        - MYSQL_DATABASE=example-api-main
        - MYSQL_USER=app
        - MYSQL_PASSWORD=app
        - MAX_CONNECTIONS=1000
      ports:
        - "4226:3306"

    webserver:
      image: nginx:alpine
      container_name: example-api-webserver
      working_dir: /var/www
      volumes:
          - .:/var/www
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
        - "4225:80"

    example-api-php:
      build: phpdocker/php-fpm/dev
      container_name: example-api-php
      working_dir: /var/www
      volumes:
        - .:/var/www
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

